apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ux3ey3j9i-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ux3ey3j9i-python 
  name: ux3ey3j9i-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: ux3ey3j9i-python 
